### ISSUE TITLE
Souhaite setup un système qui me permet de publier des articles privés, sur des urls secrètes

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/sklein.xyz#108]
Maintenant que #104 est traité, je souhaite setup un système qui me permet de publier des articles privés, sur des urls secrètes.

Todo :

- [x] Créer le repository https://github.com/stephane-klein/sklein.xyz-private/ privé
- [x] Documenter dans ce [README.md](https://github.com/stephane-klein/sklein.xyz/blob/main/README.md) où cloner ce repository
- [x] Permettre via ce frontmatter:

```
---
title: My title
page_type: blog
lang: fr
private: true
instances:
  share1:
     slug: d2317867-2ac7-453c-847c-737f20dd9f36
  "foo bar 2":
     slug: b35852f4-f533-4962-89a9-98cf5b1b5e9c 
---
```

Si un champ instance ne contient aucun uuid, alors le script doit en générer un et mettre à jour le fichier yaml

- [x] Renommer le champs `pages.private_note` en `pages.instance_name`
- [x] Renommer le champs `pages.uuid` en `pages.instance_slug`
- [x] Renommer le champs `pages.slug` en `pages.instance_path`
- [ ] Le script de chargement doit pour chaque instance insérer un ligne dans la table `pages` ou `garden`
- [x] Refactoring `/src/routes/fr/posts/[page_slug]/+page.server.js` vers `/src/routes/fr/posts/[...page_slug]/+page.server.js`
- [x] Refactoring `/src/routes/fr/garden/[page_slug]/+page.server.js` vers `/src/routes/fr/garden/[...page_slug]/+page.server.js`
- [x] Refactoring `/src/routes/en/posts/[page_slug]/+page.server.js` vers `/src/routes/en/posts/[...page_slug]/+page.server.js`
